import "./globals.css";
require("dotenv").config();

import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Next.JS 15 FullStack - localhost.4439",
  description: "Generated by localhost.4439",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: poppins.style.fontFamily }}>{children}</body>
    </html>
  );
}
